name: Deno CI

on:
    workflow_call:
        inputs:
            output:
                required: true
                type: string
            main_file:
                required: true
                type: string
        secrets:
            webhookFeishu:
                required: true
            awsAccessKey:
                required: true
            awsSecretKey:
                required: true

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2

            - name: Build executable
              run: deno compile --output ${{ inputs.output }}.exe --allow-net ${{ inputs.main_file }}

            - name: Calculate MD5 hash
              id: calculate_md5
              run: |
                  $md5 = Get-FileHash -Path ${{ inputs.output }}.exe -Algorithm SHA256
                  Write-Output "HASH=$($md5.Hash)" >> $Env:GITHUB_OUTPUT

            - name: Upload executable
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ inputs.output }}-${{ steps.calculate_md5.outputs.HASH }}
                  path: ${{ inputs.output }}.exe
        outputs:
            hash: ${{ steps.calculate_md5.outputs.HASH }}
    upload:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                  name: ${{ inputs.output }}-${{ needs.build.outputs.hash }}
                  path: ./
            - name: 上传到 s3
              uses: keithweaver/aws-s3-github-action@v1.0.0
              with:
                  command: cp
                  source: ${{ inputs.output }}.exe
                  destination: s3://xbot/${{ inputs.output }}/${{ inputs.output }}-${{ needs.build.outputs.hash }}.exe
                  aws_access_key_id: ${{ secrets.awsAccessKey }}
                  aws_secret_access_key: ${{ secrets.awsSecretKey }}
                  aws_region: us-east-1
                  flags: --acl public-read
            - name: post success message
              uses: foxundermoon/feishu-action@v2
              with:
                  url: ${{ secrets.webhookFeishu }}
                  msg_type: post
                  content: |
                      post:
                        zh_cn:
                          title: ${{ inputs.output }} 上传结果 ${{ job.status }}!
                          content:
                          - - tag: text
                              text: '部署链接: '
                            - tag: a
                              text: github action
                              href: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                          - - tag: text
                              text: 'SHA256: '
                            - tag: text
                              text: ${{ needs.build.outputs.hash }}
                          - - tag: text
                              text: '下载链接: '
                            - tag: text
                              text: https://xbot.s3.amazonaws.com/${{inputs.output}}/${{ inputs.output }}-${{  needs.build.outputs.hash }}.exe
