name: Node CI
on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      buildStage:
        required: true
        type: string
      workDir:
        required: true
        type: string
      projectPrefix:
        required: true
        type: string
    secrets:
      webhookFeishu:
        required: true
      dockerUrl:
        required: true
      dockerUsername:
        required: true
      dockerPassword:
        required: true
      dockerRepo:
        required: true
      kubeConfig:
        required: true



jobs:
  node_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    env:
      tag: ${{ secrets.dockerUrl }}/${{ secrets.dockerRepo }}/${{ inputs.projectName }}:${{ inputs.buildStage }}-${{ github.sha }}
    steps:
      - name: post message
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.webhookFeishu }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: ${{ inputs.projectName }} 开始部署
                content:
                - - tag: text
                    un_escape: true
                    text: '部署环境: ${{ inputs.buildStage }}'
                - - tag: text
                    text: '部署链接: '
                  - tag: a
                    text: github action
                    href: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.dockerUrl }}
          username: ${{ secrets.dockerUsername }}
          password: ${{ secrets.dockerPassword }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          context: .
          file: Dockerfile-${{ inputs.buildStage }}
          tags: ${{ env.tag }}
      - name: deploy to fellas cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.kubeConfig }}
          command: --namespace=${{ inputs.projectPrefix }}-${{ inputs.buildStage }} apply -f ./k8s-${{ inputs.buildStage }}.yaml || true
      - name: Tailscale
        if: ${{ inputs.buildStage == 'beta' }}
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: apply
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.kubeConfig }}
          command: --namespace=${{ inputs.projectPrefix }}-${{ inputs.buildStage }} set image deployment/${{ inputs.projectName }} ${{ inputs.projectName }}=${{ env.tag }}
      - name: post success message
        uses: foxundermoon/feishu-action@v2
        if: ${{ always() }}
        with:
          url: ${{ secrets.webhookFeishu }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: ${{ inputs.projectName }} 部署 ${{ job.status }} !
                content:
                - - tag: text
                    un_escape: true
                    text: '部署环境: ${{ inputs.buildStage }}'
                - - tag: text
                    text: '部署链接:'
                  - tag: a
                    text: github action
                    href: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
