name: Rust CI

on:
    workflow_call:
        inputs:
            region:
                required: true
                type: string
            pool_name:
                required: true
                type: string
            username:
                required: true
                type: string
            port:
                required: true
                type: string
            source:
                required: false
                type: string
            target:
                required: false
                type: string
            ips:
              required: false
              type: string
              default: ''
        secrets:
            tencentPrivateKey:
                required: true
            cfAccountId:
                required: false
            cfApiToken:
                required: false

jobs:
    build_rust:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: 'get ips'
              if: inputs.ips == ''
              uses: ReverseGame/java-build/.github/actions/cf-ips@main
              id: get_ips
              with:
                account_id: ${{ secrets.cfAccountId }}
                api_token: ${{ secrets.cfApiToken }}
                region: ${{ inputs.pool_name }}
            - name: echo
              run: |
                echo ${{ inputs.ips != '' && inputs.ips || steps.get_ips.outputs.ips }}
            - name: Copy files via SSH
              if: inputs.source != ''
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ inputs.ips != '' && inputs.ips || steps.get_ips.outputs.ips }}
                  username: ${{ inputs.username }}
                  key: ${{ secrets.tencentPrivateKey }}
                  source: ${{ inputs.source }}
                  target: ${{ inputs.target }}

            - name: init config
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ inputs.ips != '' && inputs.ips || steps.get_ips.outputs.ips }}
                sync: true
                username: ${{ inputs.username }}
                key: ${{ secrets.tencentPrivateKey }}
                port: ${{ inputs.port }}
                script: |
                  REGION=${{inputs.region}} bash rust-gateway/configs/init.sh


            - name: Multiple hosts
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ inputs.ips != '' && inputs.ips || steps.get_ips.outputs.ips }}
                sync: true
                username: ${{ inputs.username }}
                key: ${{ secrets.tencentPrivateKey }}
                port: ${{ inputs.port }}
                script: |
                  bash rust-gateway/update.sh && sleep 20
