name: Rust CI

on:
    workflow_call:
        inputs:
            region:
                required: true
                type: string
            instanceNamePrefix:
                required: true
                type: string
            username:
                required: true
                type: string
            port:
                required: true
                type: string

        secrets:
            tencentSecretId:
                required: true
            tencentSecretKey:
                required: true
            tencentPrivateKey:
                required: true

jobs:
    build_rust:
        runs-on: ubuntu-22.04
        steps:
            - name: 'get ips'
              uses: ReverseGame/java-build/.github/actions/tencent-action@main
              id: get_ips
              with:
                action: 'get_ips'
                secret_id: ${{ secrets.tencentSecreetId }}
                secret_key: ${{ secrets.tencentSecreetKey }}
                region: ${{ inputs.region }}
                instance_name_prefix: ${{ inputs.instanceNamePrefix }}
            - name: echo
              run: |
                echo ${{ steps.get_ips.outputs.ips }}
            - name: Multiple hosts
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ steps.get_ips.outputs.ips }}
                username: ${{ inputs.username }}
                key: ${{ secrets.tencentPrivateKey }}
                port: ${{ inputs.port }}
                script: |
                  echo 123 >> teste.txt