name: Rust CI

on:
  workflow_call:
    inputs:
      triggerRemoteRepo:
        required: true
        type: string
      eventType:
        required: true
        type: string
    secrets:
      triggerRepoToken:
        required: true

jobs:
  Dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Echo github
        run: |
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "PR Title: ${{ github.event.head_commit.message }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"

      - name: Trigger Remote Build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.triggerRepoToken }}
          repository: ${{ inputs.triggerRemoteRepo }}
          event-type: ${{ inputs.eventType }}
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}", "message": "${{ github.event.pull_request.title }}" }'