name: Rust CI

on:
    workflow_call:
        inputs:
            region:
                required: true
                type: string
            instanceNamePrefix:
                required: true
                type: string
            username:
                required: true
                type: string
            key:
                required: true
                type: string
            port:
                required: true
                type: string
            TENCENT_SECRET_ID:
                required: true
                type: string
            TENCENT_SECRET_KEY:
              required: true
              type: string


jobs:
    build_rust:
        runs-on: ubuntu-22.04
        steps:
            - name: 'get ips'
              uses: ReverseGame/java-build/.github/actions/tencent-action@main
              id: get_ips
              with:
                action: 'get_ips'
                secret_id: ${{ inputs.TENCENT_SECRET_ID }}
                secret_key: ${{ inputs.TENCENT_SECRET_KEY }}
                region: ${{ inputs.region }}
                instance_name_prefix: ${{ inputs.instanceNamePrefix }}
            - name: echo
              run: |
                echo ${{ steps.get_ips.outputs.result }}
            - name: Multiple hosts
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ steps.get_ips.outputs.result }}
                username: ${{ inputs.username }}
                key: ${{ inputs.key }}
                port: ${{ inputs.port }}
                script: |
                  echo 123 >> teste.txt