name: Rust CI

on:
    workflow_call:
        inputs:
            region:
                required: true
                type: string
            username:
                required: true
                type: string
            port:
                required: true
                type: string
            source:
                required: false
                type: string
            target:
                required: false
                type: string
            run_copy:
                required: false
                type: boolean
                default: true
            run_init:
                required: false
                type: boolean
                default: false
            run_multiple:
                required: false
                type: boolean
                default: true
        secrets:
            tencentPrivateKey:
                required: true
            cfAccountId:
                required: true
            cfApiToken:
                required: true

jobs:
    build_rust:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: 'get ips'
              uses: ReverseGame/java-build/.github/actions/cf-ips@main
              id: get_ips
              with:
                account_id: ${{ secrets.cfAccountId }}
                api_token: ${{ secrets.cfApiToken }}
                region: ${{ inputs.region }}
            - name: echo
              run: |
                echo ${{ steps.get_ips.outputs.ips }}
            - name: Copy files via SSH
              if: inputs.run_copy && inputs.source != ''
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ steps.get_ips.outputs.ips }}
                  username: ${{ inputs.username }}
                  key: ${{ secrets.tencentPrivateKey }}
                  source: ${{ inputs.source }}
                  target: ${{ inputs.target }}

            - name: init config
              if: inputs.run_init
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ steps.get_ips.outputs.ips }}
                sync: true
                username: ${{ inputs.username }}
                key: ${{ secrets.tencentPrivateKey }}
                port: ${{ inputs.port }}
                script: |
                  REGION=${{inputs.region}} bash rust-gateway/configs/init.sh


            - name: Multiple hosts
              if: inputs.run_multiple
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ steps.get_ips.outputs.ips }}
                sync: true
                username: ${{ inputs.username }}
                key: ${{ secrets.tencentPrivateKey }}
                port: ${{ inputs.port }}
                script: |
                  bash rust-gateway/update.sh && sleep 20
