name: Tauri CI Dispatch

on:
  workflow_call:
    inputs:
      buildStage:
        required: true
        type: string
      nodeVersion:
        required: false
        type: string
        default: "lts/*"
      tauriVersion:
        required: false
        type: string
        default: "1"
      awsRegion:
        required: true
        type: string
      buildFeishuWebhook:
        required: false
        type: string
      releaseFeishuWebhook:
        required: false
        type: string
      bucket:
        required: true
        type: string
    secrets:
      awsAccessKey:
        required: true
      awsSecretKey:
        required: true
      tauriPrivateKey:
        required: true
      tauriKeyPassword:
        required: true
      patToken:
        required: true

jobs:
  pr_new_version:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Echo client_payload
        run: |
          echo "client_payload sha: ${{ github.event.client_payload.sha }}"
          echo "client_payload pr_title: ${{ github.event.client_payload.message }}"
          echo "client_payload repository: ${{ github.event.client_payload.repository }}"
      - name: Checkout code (检出代码)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.patToken }}
          submodules: recursive
          fetch-depth: 0
      - name: show dir list
        run: ls -a
      - name: Update submodule SHAs
        run: |
          echo $(pwd)
          echo "master SHA: $(git rev-parse HEAD)"
          repository="${{ github.event.client_payload.repository }}"
          echo "Updating repository: $repository"
          # 从完整仓库路径提取仓库名 (如: ReverseGame/reverse-proxy-test -> reverse-proxy-test)
          repo_name=$(basename $repository)
          echo "Local submodule path: $repo_name"
          git -C $repo_name fetch origin ${{ github.event.client_payload.sha }}
          git -C $repo_name checkout ${{ github.event.client_payload.sha }} --force
          cd $repo_name 
          git rev-parse HEAD

      - name: Setup Node.js  environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Increment version
        id: version
        run: |
          npm install -g pnpm
          pnpm update-version

      - name: Set PR body based on repository
        id: pr_body
        run: |
          repository="${{ github.event.client_payload.repository }}"
          if [ "$repository" == "reverse-bot-rs" ]; then
            echo "body=xbot 内核更新" >> $GITHUB_OUTPUT
          elif [ "$repository" == "reverse-proxy-test" ]; then
            echo "body=代理测试模块更新" >> $GITHUB_OUTPUT
          else
            echo "body=优化已知问题" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          add-paths: |
            package.json
            src-tauri/*
            ${{ github.event.client_payload.repository }}
          commit-message: "[create-pull-request] ${{ github.event.client_payload.message }}"
          title: "[create-pull-request] ${{ github.event.client_payload.message }}"
          body: "${{ steps.pr_body.outputs.body }}"

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --admin --merge
        env:
          GH_TOKEN: ${{ secrets.patToken }}

      - name: post success message
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ inputs.buildFeishuWebhook }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: PR 合并成功
                content:
                - - tag: text
                    text: 'PR链接: '
                  - tag: a
                    text: 点击跳转
                    href: ${{ steps.cpr.outputs.pull-request-url }}
