name: Tauri CI Dispatch

on:
  workflow_call:
    inputs:
      buildStage:
        required: true
        type: string
      nodeVersion:
        required: false
        type: string
        default: "lts/*"
      tauriVersion:
        required: false
        type: string
        default: "1"
      awsRegion:
        required: true
        type: string
      buildFeishuWebhook:
        required: false
        type: string
      releaseFeishuWebhook:
        required: false
        type: string
      bucket:
        required: true
        type: string
    secrets:
      awsAccessKey:
        required: true
      awsSecretKey:
        required: true
      tauriPrivateKey:
        required: true
      tauriKeyPassword:
        required: true
      patToken:
        required: true

jobs:
  pr_new_version:
    runs-on: "rust-windows"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Echo client_payload
        run: |
          echo "client_payload sha: ${{ github.event.client_payload.sha }}"
          echo "client_payload pr_title: ${{ github.event.client_payload.message }}"
      - name: Checkout code (检出代码)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.patToken }}
          submodules: recursive
          fetch-depth: 0

#      - name: Update submodule SHAs
#        run: |
#          echo "master SHA: $(git rev-parse HEAD)"
#          $repository = Split-Path ${{ github.event.client_payload.repository }} -Leaf
#          git -C $repository fetch origin ${{ github.event.client_payload.sha }}
#          git -C $repository checkout ${{ github.event.client_payload.sha }} --force

      - name: Increment version
        id: version
        run: |
          $content = Get-Content package.json -Raw
          $version = ($content | ConvertFrom-Json).version
          $parts = $version.Split('.')
          $parts[2] = [int]$parts[2] + 1
          $newVersion = $parts -join '.'
          $content = $content -replace """version"": ""$version""", """version"": ""$newVersion"""
          Set-Content -Path package.json -Value $content

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          add-paths: package.json
          commit-message: '[create-pull-request] ${{ github.event.client_payload.message }}'
          title: '[create-pull-request] ${{ github.event.client_payload.message }}'

      - name: Post Message (发送飞书 Webhook 消息)
        uses: Comori/feishu@v0.0.5
        if: success() && ${{ inputs.buildFeishuWebhook }}
        with:
          webhook-url: ${{ inputs.buildFeishuWebhook }}
          msg-type: cardkit
          cardkit-id: AAq15syMYoq55
          cardkit-version: 0.0.3
          content: |
            title= Xbot-gui PR待审核
            url = ${{ steps.cpr.outputs.pull-request-url }}